services:
  mongodb:
    image: mongo:7
    container_name: luxestay-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - luxestay_mongo_data:/data/db

volumes:
  luxestay_mongo_data:
